-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Precipitation"
(
    country text COLLATE pg_catalog."default",
    location_name text COLLATE pg_catalog."default",
    latitude real,
    longitude real,
    condition_text text COLLATE pg_catalog."default",
    precip_mm real,
	CONSTRAINT "Precipitation" PRIMARY KEY ("country")
);

CREATE TABLE IF NOT EXISTS public.cloud_cover
(
    cloud integer,
    visibility_km numeric,
    visibility_miles numeric,
    air_quality numeric,
	CONSTRAINT "cloud_cover" PRIMARY KEY (
		"cloud"
	)
);

CREATE TABLE IF NOT EXISTS public.moon_vs_air_quality
(
    air_quality numeric,
    moon_illumination integer,
	CONSTRAINT "moon_vs_air_quality" PRIMARY KEY (
		"air_quality"
	)
);

CREATE TABLE IF NOT EXISTS public.temperature_fahrenheit
(
	country text COLLATE pg_catalog."default",
    latitude real,
    longitude real,
    temperature_fahrenheit real,
	CONSTRAINT "temperature_fahrenheit" PRIMARY KEY (
		"temperature_fahrenheit"
	)
);

ALTER TABLE "temperature_fahrenheit" ADD CONSTRAINT "temperature_fahrenheit_country" FOREIGN KEY("country")
REFERENCES "Precipitation" ("country");

ALTER TABLE "cloud_cover" ADD CONSTRAINT "cloud_cover_air_quality" FOREIGN KEY("air_quality")
REFERENCES "moon_vs_air_quality" ("air_quality");

ALTER TABLE "cloud_cover" ADD CONSTRAINT "cloud_cover_air_quality" FOREIGN KEY("air_quality")
REFERENCES "moon_vs_air_quality" ("air_quality");

END;

SELECT *
FROM cloud_cover
